DECLARE @EnterAcademicYear NVARCHAR(4); -- Declare a user input variable
SET @EnterAcademicYear = 2025; -- Manually set the user input for an academic year

WITH
CTE_USERDEFINEDIND AS (
	SELECT
	[USERDEFINEDIND].[PEOPLE_CODE_ID],
	[USERDEFINEDIND].[ALBERTASTUDENTID]
	FROM [USERDEFINEDIND]
),

CTE_PEOPLE AS (
	SELECT
	[PEOPLE].[PEOPLE_CODE_ID],
	CONVERT(CHAR(8), [PEOPLE].[BIRTH_DATE], 112) AS 'CUSTOM_BIRTH_DATE' -- Convert datetime into YYYYMMDD
	FROM [PEOPLE]
),

CTE_DEMOGRAPHICS_BY_TERM AS (
	SELECT
	[DEMOGRAPHICS].[PEOPLE_CODE_ID],
	[DEMOGRAPHICS].[ACADEMIC_TERM],
	[DEMOGRAPHICS].[ACADEMIC_YEAR],
	[DEMOGRAPHICS].[ACADEMIC_SESSION],
	[DEMOGRAPHICS].[ETHNICITY],
	CASE
		WHEN [DEMOGRAPHICS].[ETHNICITY] IS NULL OR [DEMOGRAPHICS].[ETHNICITY] = '' THEN ''
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'STATUS' THEN '1'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'NONSTA' THEN '2'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'METIS' THEN '3'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'INUIT' THEN '4'
		ELSE NULL
	END AS 'CONVERTED_ETHNICITY',
	[DEMOGRAPHICS].[GENDER],
	[DEMOGRAPHICS].[CITIZENSHIP],
	[CODE_COUNTRY].[CODE_XVAL],
	[DEMOGRAPHICS].[VISA],
	CASE
		WHEN [DEMOGRAPHICS].[VISA] IS NULL OR [DEMOGRAPHICS].[VISA] = '' OR [DEMOGRAPHICS].[VISA] = 'UNKN' THEN '9'
		WHEN [DEMOGRAPHICS].[VISA] = 'CDN' THEN '1'
		WHEN [DEMOGRAPHICS].[VISA] = 'PERM' THEN '2'
		WHEN [DEMOGRAPHICS].[VISA] = 'SVIS' THEN '3'
		WHEN [DEMOGRAPHICS].[VISA] = 'OVIS' THEN '4'
		WHEN [DEMOGRAPHICS].[VISA] = 'REFG' THEN '6'
		ELSE NULL
	END AS 'CONVERTED_VISA',
	[DEMOGRAPHICS].[PRIMARY_LANGUAGE],
	CASE
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] IS NULL OR [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = '' OR [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'UNKNOW' THEN 'UND'
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'ENGL' THEN 'ENG'
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'FRENCH' THEN 'FRE'
		ELSE 'OTH'
	END AS 'CONVERTED_LANGUAGE',
	[DEMOGRAPHICS].[HOME_LANGUAGE]
	FROM [DEMOGRAPHICS]
	LEFT JOIN [ACADEMICCALENDAR]
	ON
	[DEMOGRAPHICS].[ACADEMIC_TERM] = [ACADEMICCALENDAR].[ACADEMIC_TERM] AND
	[DEMOGRAPHICS].[ACADEMIC_YEAR] = [ACADEMICCALENDAR].[ACADEMIC_YEAR] AND
	[DEMOGRAPHICS].[ACADEMIC_SESSION] = [ACADEMICCALENDAR].[ACADEMIC_SESSION]
	LEFT JOIN [CODE_COUNTRY]
	ON
	[DEMOGRAPHICS].[CITIZENSHIP] = [CODE_COUNTRY].[CODE_VALUE_KEY]
	WHERE
	[DEMOGRAPHICS].[ACADEMIC_SESSION] <> '' AND
	[CODE_COUNTRY].[STATUS] = 'A' AND
	[ACADEMICCALENDAR].[TRUE_ACADEMIC_YEAR] = @EnterAcademicYear
),


CTE_DEMOGRAPHICS_GENERAL AS (
	SELECT
	[DEMOGRAPHICS].[PEOPLE_CODE_ID],
	[DEMOGRAPHICS].[ACADEMIC_TERM],
	[DEMOGRAPHICS].[ACADEMIC_YEAR],
	[DEMOGRAPHICS].[ACADEMIC_SESSION],
	[DEMOGRAPHICS].[ETHNICITY],
	CASE
		WHEN [DEMOGRAPHICS].[ETHNICITY] IS NULL OR [DEMOGRAPHICS].[ETHNICITY] = '' THEN ''
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'STATUS' THEN '1'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'NONSTA' THEN '2'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'METIS' THEN '3'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'INUIT' THEN '4'
		ELSE NULL
	END AS 'CONVERTED_ETHNICITY',
	[DEMOGRAPHICS].[GENDER],
	[DEMOGRAPHICS].[CITIZENSHIP],
	[CODE_COUNTRY].[CODE_XVAL],
	[DEMOGRAPHICS].[VISA],
	CASE
		WHEN [DEMOGRAPHICS].[VISA] IS NULL OR [DEMOGRAPHICS].[VISA] = '' OR [DEMOGRAPHICS].[VISA] = 'UNKN' THEN '9'
		WHEN [DEMOGRAPHICS].[VISA] = 'CDN' THEN '1'
		WHEN [DEMOGRAPHICS].[VISA] = 'PERM' THEN '2'
		WHEN [DEMOGRAPHICS].[VISA] = 'SVIS' THEN '3'
		WHEN [DEMOGRAPHICS].[VISA] = 'OVIS' THEN '4'
		WHEN [DEMOGRAPHICS].[VISA] = 'REFG' THEN '6'
		ELSE NULL
	END AS 'CONVERTED_VISA',
	[DEMOGRAPHICS].[PRIMARY_LANGUAGE],
	CASE
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] IS NULL OR [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = '' OR [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'UNKNOW' THEN 'UND'
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'ENGL' THEN 'ENG'
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'FRENCH' THEN 'FRE'
		ELSE 'OTH'
	END AS 'CONVERTED_LANGUAGE',
	[DEMOGRAPHICS].[HOME_LANGUAGE]
	FROM [DEMOGRAPHICS]
	LEFT JOIN [CODE_COUNTRY]
	ON
	[DEMOGRAPHICS].[CITIZENSHIP] = [CODE_COUNTRY].[CODE_VALUE_KEY]
	WHERE
	[DEMOGRAPHICS].[ACADEMIC_TERM] = '' AND
	[DEMOGRAPHICS].[ACADEMIC_YEAR] = '' AND
	[DEMOGRAPHICS].[ACADEMIC_SESSION] = ''
),

CTE_PROGRAMLOADS AS (
	SELECT
	[PROGRAMLOADS].[TRUE_ACADEMIC_YEAR],
	[PROGRAMLOADS].[PROGRAMID],
	[PROGRAMLOADS].[LERSPROGRAM],
	[PROGRAMLOADS].[LERSID]
	FROM [PROGRAMLOADS]
	WHERE [PROGRAMLOADS].[TRUE_ACADEMIC_YEAR] = @EnterAcademicYear
), 

CTE_LINC_HOURS AS (
	SELECT
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION],
	SUM([SECTIONS].[CONTACT_HR_SESSION]) AS 'LINC_HOURS'
	FROM TRANSCRIPTDETAIL

	LEFT JOIN [SECTIONS]
	ON
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM] = [SECTIONS].[ACADEMIC_TERM] AND
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR] = [SECTIONS].[ACADEMIC_YEAR] AND
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION] = [SECTIONS].[ACADEMIC_SESSION] AND
	[TRANSCRIPTDETAIL].[EVENT_ID] = [SECTIONS].[EVENT_ID] AND
	[TRANSCRIPTDETAIL].[EVENT_SUB_TYPE] = [SECTIONS].[EVENT_SUB_TYPE] AND
	[TRANSCRIPTDETAIL].[SECTION] = [SECTIONS].[SECTION]

	LEFT JOIN [ACADEMICCALENDAR]
	ON
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM] = [ACADEMICCALENDAR].[ACADEMIC_TERM] AND
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR] = [ACADEMICCALENDAR].[ACADEMIC_YEAR] AND
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION] = [ACADEMICCALENDAR].[ACADEMIC_SESSION]

	WHERE
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION] = '01' AND
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT] = 'A' AND
	[TRANSCRIPTDETAIL].[EVENT_ID] LIKE 'LINC%' AND
	[ACADEMICCALENDAR].[TRUE_ACADEMIC_YEAR] = @EnterAcademicYear

	GROUP BY
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION]
),

CTE_ONLINE_COURSE_COUNT AS (
	SELECT
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION],
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT],
	COUNT([TRANSCRIPTDETAIL].[SECTION]) AS 'ONLINE_COURSE_COUNT'
	FROM [TRANSCRIPTDETAIL]

	WHERE
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT] = 'A' AND
	([TRANSCRIPTDETAIL].[SECTION] LIKE 'INT%' OR -- Conditons to be reviewed by OR
	[TRANSCRIPTDETAIL].[SECTION] LIKE 'IT%' OR -- Conditons to be reviewed by OR
	[TRANSCRIPTDETAIL].[SECTION] = 'HF') -- Conditons to be reviewed by OR

	GROUP BY
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION],
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT]
),

CTE_WIL_COURSE_COUNT AS (
	SELECT
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION],
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT],
	COUNT([TRANSCRIPTDETAIL].[EVENT_SUB_TYPE]) AS 'WIL_COURSE_COUNT'
	FROM [TRANSCRIPTDETAIL]

	WHERE
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT] = 'A' AND
	[TRANSCRIPTDETAIL].[EVENT_SUB_TYPE] IN ('CLIN','LECW','PRAC') -- Conditons to be reviewed by OR

	GROUP BY
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION],
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT]
),

CTE_SOURCE_LOCATION AS (
	SELECT
		A.[PEOPLE_ORG_CODE_ID],
		A.[ZIP_CODE] AS [ZIP_CODE_ORIGINAL],
		CASE
			WHEN NULLIF(REPLACE(A.[ZIP_CODE], ' ', ''), '') IS NULL THEN
				CASE 
					WHEN A.[COUNTRY] IN ('CA','800') THEN '999999'
					ELSE '888888'
				END
			ELSE
				CASE 
					WHEN B.[CODE_XVAL] = 'US'
						THEN LEFT(REPLACE(A.[ZIP_CODE], ' ', ''), 5)
					ELSE
						LEFT(REPLACE(A.[ZIP_CODE], ' ', ''), 6)
				END
		END AS [ZIP_CODE_CLEAN],

		A.[COUNTRY],
		B.[CODE_XVAL],
		CASE
			WHEN A.[COUNTRY] = 'CA' THEN A.[COUNTRY]
			ELSE B.[CODE_XVAL]
		END AS 'COUNTRY_CLEAN',
		A.[START_DATE]

	FROM (
		SELECT TOP (1) WITH TIES
			[ADDRESSSCHEDULE].[PEOPLE_ORG_CODE_ID],
			[ADDRESSSCHEDULE].[ZIP_CODE],
			[ADDRESSSCHEDULE].[COUNTRY],
			[ADDRESSSCHEDULE].[START_DATE]
		FROM [ADDRESSSCHEDULE]
		WHERE [ADDRESSSCHEDULE].[ADDRESS_TYPE] = 'HOME'
		ORDER BY ROW_NUMBER() OVER (
			PARTITION BY [ADDRESSSCHEDULE].[PEOPLE_ORG_CODE_ID]
			ORDER BY
				CASE 
					WHEN [ADDRESSSCHEDULE].[START_DATE] IS NULL THEN 1 
					ELSE 0 
				END,
				[ADDRESSSCHEDULE].[START_DATE] ASC
		)
	) AS A
	LEFT JOIN [CODE_COUNTRY] AS B
		ON A.[COUNTRY] = B.[CODE_VALUE_KEY]
)

SELECT
[ACADEMICCALENDAR].[TRUE_ACADEMIC_YEAR] AS 'AcademicYear',
'KC' AS 'Provider',
[USERDEFINEDIND].[ALBERTASTUDENTID] AS 'ASN',
[ACADEMIC].[PEOPLE_ID] AS 'StudentID',
[CTE_PEOPLE].[CUSTOM_BIRTH_DATE] AS 'Birthdate',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[GENDER] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[GENDER]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[GENDER]
END AS 'Gender',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_LANGUAGE] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_LANGUAGE]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[CONVERTED_LANGUAGE]
END AS 'Language',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[CODE_XVAL] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[CODE_XVAL]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[CODE_XVAL]
END AS 'CountryOfCitizenship',
[CTE_SOURCE_LOCATION].[COUNTRY_CLEAN] AS 'SourceCountry',
[CTE_SOURCE_LOCATION].[ZIP_CODE_CLEAN] AS 'SourcePostalCode',
[CTE_PROGRAMLOADS].[LERSPROGRAM] AS 'ProgramID',
[CTE_PROGRAMLOADS].[LERSID] AS 'SpecializationID',
CASE
	WHEN [CTE_PROGRAMLOADS].[LERSID] = 'POW3' THEN '05'
	WHEN [CTE_PROGRAMLOADS].[LERSID] = 'POW4' THEN '05'
	WHEN [CTE_PROGRAMLOADS].[LERSID] = 'PAHET' THEN '03'
	WHEN [CTE_PROGRAMLOADS].[LERSID] = 'AHD' THEN '03'
	ELSE '02'
END AS 'ProviderLocation',
CASE
	WHEN [ACADEMIC].[ACADEMIC_TERM] = 'SUMMER' THEN '1'
	WHEN [ACADEMIC].[ACADEMIC_TERM] = 'FALL' THEN '2'
	WHEN [ACADEMIC].[ACADEMIC_TERM] = 'WINTER' THEN '3'
	WHEN [ACADEMIC].[ACADEMIC_TERM] = 'SPRING' THEN '4'
	ELSE NULL
END AS 'Session',
[ACADEMIC].[CLASS_LEVEL] AS 'YearOfStudy',
CASE
	WHEN [ACADEMIC].[FULL_PART_DISP_WITHDRAWN] = '1' THEN [FULL_PART_LOOKUP_TABLE].[CODE_XVAL]
	WHEN [ACADEMIC].[FULL_PART_DISP_WITHDRAWN] = '0' THEN [FULL_PART_NON_WITHDRAWN_LOOKUP_TABLE].[CODE_XVAL]
	ELSE NULL
END AS 'RegistrationStatus',
CASE
	WHEN [ACADEMIC].[CURRICULUM] = 'LINC13' THEN [CTE_LINC_HOURS].[LINC_HOURS]
	ELSE [ACADEMIC].[CREDITS]
END AS 'CreditsEnrolled',
CASE
	WHEN [CTE_ONLINE_COURSE_COUNT].[ONLINE_COURSE_COUNT] IS NULL THEN 'N'
	ELSE 'Y'
END AS 'OnlineDistanceDelivery',
CASE
	WHEN [CTE_WIL_COURSE_COUNT].[WIL_COURSE_COUNT] IS NULL THEN 'N'
	ELSE 'Y'
END AS 'WorkIntegratedLearning',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_VISA] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_VISA]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[CONVERTED_VISA]
END AS 'LegalStatus',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_ETHNICITY] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_ETHNICITY]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[CONVERTED_ETHNICITY]
END AS 'IndigenousIndicator',
CASE
	WHEN [ACADEMIC].[ENROLL_SEPARATION] = 'ENRO' THEN '0'
	WHEN [ACADEMIC].[ENROLL_SEPARATION] = 'GRAD' THEN '1'
	WHEN [ACADEMIC].[ENROLL_SEPARATION] = 'WITH' OR [ACADEMIC].[ENROLL_SEPARATION] = 'DISM' THEN '2'
	WHEN [ACADEMIC].[ENROLL_SEPARATION] = 'BRKD' THEN '5'
	ELSE [ACADEMIC].[ENROLL_SEPARATION]
END AS 'CompletionStatus'

FROM [ACADEMIC]

LEFT JOIN [ACADEMICCALENDAR]
ON
[ACADEMIC].[ACADEMIC_TERM] = [ACADEMICCALENDAR].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [ACADEMICCALENDAR].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [ACADEMICCALENDAR].[ACADEMIC_SESSION]

LEFT JOIN [CTE_PEOPLE]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_PEOPLE].[PEOPLE_CODE_ID]

LEFT JOIN [USERDEFINEDIND]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [USERDEFINEDIND].[PEOPLE_CODE_ID]

LEFT JOIN [CTE_DEMOGRAPHICS_BY_TERM]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_DEMOGRAPHICS_BY_TERM].[PEOPLE_CODE_ID] AND
[ACADEMIC].[ACADEMIC_TERM] = [CTE_DEMOGRAPHICS_BY_TERM].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [CTE_DEMOGRAPHICS_BY_TERM].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [CTE_DEMOGRAPHICS_BY_TERM].[ACADEMIC_SESSION]

LEFT JOIN [CTE_DEMOGRAPHICS_GENERAL]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_DEMOGRAPHICS_GENERAL].[PEOPLE_CODE_ID]

LEFT JOIN [CTE_PROGRAMLOADS]
ON
[ACADEMIC].[CURRICULUM] = [CTE_PROGRAMLOADS].[PROGRAMID]

LEFT JOIN [CODE_FULLPARTFLAG] AS FULL_PART_LOOKUP_TABLE
ON
[ACADEMIC].[FULL_PART] = [FULL_PART_LOOKUP_TABLE].[CODE_VALUE_KEY]

LEFT JOIN [CODE_FULLPARTFLAG] AS FULL_PART_NON_WITHDRAWN_LOOKUP_TABLE
ON
[ACADEMIC].[FULL_PART_NON_WITHDRAWN] = [FULL_PART_NON_WITHDRAWN_LOOKUP_TABLE].[CODE_VALUE_KEY]

LEFT JOIN [CODE_CURRICULUM]
ON
[ACADEMIC].[CURRICULUM] = [CODE_CURRICULUM].[CODE_VALUE_KEY]

LEFT JOIN [CTE_LINC_HOURS]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_LINC_HOURS].[PEOPLE_CODE_ID] AND
[ACADEMIC].[ACADEMIC_TERM] = [CTE_LINC_HOURS].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [CTE_LINC_HOURS].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [CTE_LINC_HOURS].[ACADEMIC_SESSION]

LEFT JOIN [CTE_ONLINE_COURSE_COUNT]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_ONLINE_COURSE_COUNT].[PEOPLE_CODE_ID] AND
[ACADEMIC].[ACADEMIC_TERM] = [CTE_ONLINE_COURSE_COUNT].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [CTE_ONLINE_COURSE_COUNT].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [CTE_ONLINE_COURSE_COUNT].[ACADEMIC_SESSION]

LEFT JOIN [CTE_WIL_COURSE_COUNT]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_WIL_COURSE_COUNT].[PEOPLE_CODE_ID] AND
[ACADEMIC].[ACADEMIC_TERM] = [CTE_WIL_COURSE_COUNT].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [CTE_WIL_COURSE_COUNT].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [CTE_WIL_COURSE_COUNT].[ACADEMIC_SESSION]

LEFT JOIN [CTE_SOURCE_LOCATION]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_SOURCE_LOCATION].[PEOPLE_ORG_CODE_ID]

WHERE
[CODE_CURRICULUM].[LONG_DESC] NOT LIKE 'APPR%' AND
[ACADEMIC].[CURRICULUM] NOT LIKE 'DUAL%' AND
([ACADEMIC].[ACADEMIC_SESSION] = '01' OR
[ACADEMIC].[PROGRAM] = 'CREDIT' OR
[ACADEMIC].[DEGREE] <> 'CONED') AND
[ACADEMIC].[ACADEMIC_SESSION] <> '' AND
[ACADEMIC].[STATUS] <> 'N' AND
[ACADEMIC].[ACADEMIC_FLAG] = 'Y' AND
[ACADEMIC].[ENROLL_SEPARATION] IN ('APPR','BRKD','DISM','ENRO','GRAD','WITH') AND
(CASE
	WHEN [ACADEMIC].[FULL_PART_DISP_WITHDRAWN] = '1' THEN [FULL_PART_LOOKUP_TABLE].[CODE_XVAL]
	WHEN [ACADEMIC].[FULL_PART_DISP_WITHDRAWN] = '0' THEN [FULL_PART_NON_WITHDRAWN_LOOKUP_TABLE].[CODE_XVAL]
	ELSE NULL
END) IN ('F','L','N','P') AND
[ACADEMICCALENDAR].[TRUE_ACADEMIC_YEAR] = @EnterAcademicYear

ORDER BY [ACADEMIC].[PEOPLE_ID] ASC


