DECLARE @EnterAcademicYear NVARCHAR(4); -- Declare a user input variable
SET @EnterAcademicYear = 2025; -- Manually set the user input for an academic year

WITH

/* Common Table Expression (CTE) that returns a table of "Active" country codes. 
This will be used as a lookup table to convert Power Campus country codes into LERS country codes. */
CTE_CODE_COUNTRY_ACTIVE AS (
	SELECT
	[CODE_COUNTRY].[CODE_VALUE_KEY],
	[CODE_COUNTRY].[CODE_XVAL]
	FROM [CODE_COUNTRY]
	WHERE [CODE_COUNTRY].[STATUS] = 'A'
),

/* Common Table Expression (CTE) that returns a table of Alberta Student Numbers (ASNs) for all student. 
This will be used as a lookup table for the main query. */
CTE_USERDEFINEDIND AS (
	SELECT
	[USERDEFINEDIND].[PEOPLE_CODE_ID],
	[USERDEFINEDIND].[ALBERTASTUDENTID]
	FROM [USERDEFINEDIND]
),

/* Common Table Expression (CTE) that returns a table of birth dates for all student. 
Birth date is converted from DATETIME datatype into CHAR datatype in the format of 'YYYYMMDD'. 
This will be used as a lookup table for the main query. */
CTE_PEOPLE AS (
	SELECT
	[PEOPLE].[PEOPLE_CODE_ID],
	CONVERT(CHAR(8), [PEOPLE].[BIRTH_DATE], 112) AS 'CUSTOM_BIRTH_DATE' -- Convert datetime into YYYYMMDD
	FROM [PEOPLE]
),

/* Common Table Expression (CTE) that returns a table of demographics data for all student, by academic term, for the user input's true academic year. 
[DEMOGRAPHICS].[CITIZENSHIP] is converted into LERS country code using CTE_CODE_COUNTRY_ACTIVE.
Other columns are also converted to required LERS reporting format, where needed. 
This will be used as the primary demographics lookup table for the main query. */
CTE_DEMOGRAPHICS_BY_TERM AS (
	SELECT
	[DEMOGRAPHICS].[PEOPLE_CODE_ID],
	[DEMOGRAPHICS].[ACADEMIC_TERM],
	[DEMOGRAPHICS].[ACADEMIC_YEAR],
	[DEMOGRAPHICS].[ACADEMIC_SESSION],
	[DEMOGRAPHICS].[ETHNICITY],
	CASE
		WHEN [DEMOGRAPHICS].[ETHNICITY] IS NULL OR [DEMOGRAPHICS].[ETHNICITY] = '' THEN ''
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'STATUS' THEN '1'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'NONSTA' THEN '2'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'METIS' THEN '3'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'INUIT' THEN '4'
		ELSE NULL
	END AS 'CONVERTED_ETHNICITY',
	[DEMOGRAPHICS].[GENDER],
	[DEMOGRAPHICS].[CITIZENSHIP],
	[CTE_CODE_COUNTRY_ACTIVE].[CODE_XVAL],
	[DEMOGRAPHICS].[VISA],
	CASE
		WHEN [DEMOGRAPHICS].[VISA] IS NULL OR [DEMOGRAPHICS].[VISA] = '' OR [DEMOGRAPHICS].[VISA] = 'UNKN' THEN '9'
		WHEN [DEMOGRAPHICS].[VISA] = 'CDN' THEN '1'
		WHEN [DEMOGRAPHICS].[VISA] = 'PERM' THEN '2'
		WHEN [DEMOGRAPHICS].[VISA] = 'SVIS' THEN '3'
		WHEN [DEMOGRAPHICS].[VISA] = 'OVIS' THEN '4'
		WHEN [DEMOGRAPHICS].[VISA] = 'REFG' THEN '6'
		ELSE NULL
	END AS 'CONVERTED_VISA',
	[DEMOGRAPHICS].[PRIMARY_LANGUAGE],
	CASE
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] IS NULL OR [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = '' OR [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'UNKNOW' THEN 'UND'
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'ENGL' THEN 'ENG'
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'FRENCH' THEN 'FRE'
		ELSE 'OTH'
	END AS 'CONVERTED_LANGUAGE',
	[DEMOGRAPHICS].[HOME_LANGUAGE]
	FROM [DEMOGRAPHICS]
	LEFT JOIN [ACADEMICCALENDAR]
	ON
	[DEMOGRAPHICS].[ACADEMIC_TERM] = [ACADEMICCALENDAR].[ACADEMIC_TERM] AND
	[DEMOGRAPHICS].[ACADEMIC_YEAR] = [ACADEMICCALENDAR].[ACADEMIC_YEAR] AND
	[DEMOGRAPHICS].[ACADEMIC_SESSION] = [ACADEMICCALENDAR].[ACADEMIC_SESSION]
	LEFT JOIN [CTE_CODE_COUNTRY_ACTIVE]
	ON
	[DEMOGRAPHICS].[CITIZENSHIP] = [CTE_CODE_COUNTRY_ACTIVE].[CODE_VALUE_KEY]
	WHERE
	[DEMOGRAPHICS].[ACADEMIC_SESSION] <> '' AND
	[ACADEMICCALENDAR].[TRUE_ACADEMIC_YEAR] = @EnterAcademicYear
),

/* Common Table Expression (CTE) that returns a table of demographics data for all student, for the lastest demographics data, for the user input's true academic year. 
[DEMOGRAPHICS].[CITIZENSHIP] is converted into LERS country code using CTE_CODE_COUNTRY_ACTIVE.
Other columns are also converted to required LERS reporting format, where needed. 
This will be used as the secondary demographics lookup table for the main query, for when the primary demographics lookup table cannot be used. */
CTE_DEMOGRAPHICS_GENERAL AS (
	SELECT
	[DEMOGRAPHICS].[PEOPLE_CODE_ID],
	[DEMOGRAPHICS].[ACADEMIC_TERM],
	[DEMOGRAPHICS].[ACADEMIC_YEAR],
	[DEMOGRAPHICS].[ACADEMIC_SESSION],
	[DEMOGRAPHICS].[ETHNICITY],
	CASE
		WHEN [DEMOGRAPHICS].[ETHNICITY] IS NULL OR [DEMOGRAPHICS].[ETHNICITY] = '' THEN ''
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'STATUS' THEN '1'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'NONSTA' THEN '2'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'METIS' THEN '3'
		WHEN [DEMOGRAPHICS].[ETHNICITY] = 'INUIT' THEN '4'
		ELSE NULL
	END AS 'CONVERTED_ETHNICITY',
	[DEMOGRAPHICS].[GENDER],
	[DEMOGRAPHICS].[CITIZENSHIP],
	[CTE_CODE_COUNTRY_ACTIVE].[CODE_XVAL],
	[DEMOGRAPHICS].[VISA],
	CASE
		WHEN [DEMOGRAPHICS].[VISA] IS NULL OR [DEMOGRAPHICS].[VISA] = '' OR [DEMOGRAPHICS].[VISA] = 'UNKN' THEN '9'
		WHEN [DEMOGRAPHICS].[VISA] = 'CDN' THEN '1'
		WHEN [DEMOGRAPHICS].[VISA] = 'PERM' THEN '2'
		WHEN [DEMOGRAPHICS].[VISA] = 'SVIS' THEN '3'
		WHEN [DEMOGRAPHICS].[VISA] = 'OVIS' THEN '4'
		WHEN [DEMOGRAPHICS].[VISA] = 'REFG' THEN '6'
		ELSE NULL
	END AS 'CONVERTED_VISA',
	[DEMOGRAPHICS].[PRIMARY_LANGUAGE],
	CASE
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] IS NULL OR [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = '' OR [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'UNKNOW' THEN 'UND'
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'ENGL' THEN 'ENG'
		WHEN [DEMOGRAPHICS].[PRIMARY_LANGUAGE] = 'FRENCH' THEN 'FRE'
		ELSE 'OTH'
	END AS 'CONVERTED_LANGUAGE',
	[DEMOGRAPHICS].[HOME_LANGUAGE]
	FROM [DEMOGRAPHICS]
	LEFT JOIN [CTE_CODE_COUNTRY_ACTIVE]
	ON
	[DEMOGRAPHICS].[CITIZENSHIP] = [CTE_CODE_COUNTRY_ACTIVE].[CODE_VALUE_KEY]
	WHERE
	[DEMOGRAPHICS].[ACADEMIC_TERM] = '' AND
	[DEMOGRAPHICS].[ACADEMIC_YEAR] = '' AND
	[DEMOGRAPHICS].[ACADEMIC_SESSION] = ''
),

/* Common Table Expression (CTE) that returns a table of LERS Program ID and LERS Specialization ID, for the user input's true academic year. 
This will be used as a lookup table to convert Power Campus Program ID into LERS Program ID (Equivalent to Power Campus Department ID) and LERS Specialization ID (Equivalent to Power Campus Program ID). */
CTE_PROGRAMLOADS AS (
	SELECT
	[PROGRAMLOADS].[TRUE_ACADEMIC_YEAR],
	[PROGRAMLOADS].[PROGRAMID],
	[PROGRAMLOADS].[LERSPROGRAM],
	[PROGRAMLOADS].[LERSID]
	FROM [PROGRAMLOADS]
	WHERE [PROGRAMLOADS].[TRUE_ACADEMIC_YEAR] = @EnterAcademicYear
), 

/* Common Table Expression (CTE) that returns a table of class hours for students in the LINC program, for the user input's true academic year. 
This will be used as a lookup table for LERS Credits column, only for LINC program enrolment data. */
CTE_LINC_HOURS AS (
	SELECT
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION],
	SUM([SECTIONS].[CONTACT_HR_SESSION]) AS 'LINC_HOURS'
	FROM TRANSCRIPTDETAIL

	LEFT JOIN [SECTIONS]
	ON
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM] = [SECTIONS].[ACADEMIC_TERM] AND
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR] = [SECTIONS].[ACADEMIC_YEAR] AND
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION] = [SECTIONS].[ACADEMIC_SESSION] AND
	[TRANSCRIPTDETAIL].[EVENT_ID] = [SECTIONS].[EVENT_ID] AND
	[TRANSCRIPTDETAIL].[EVENT_SUB_TYPE] = [SECTIONS].[EVENT_SUB_TYPE] AND
	[TRANSCRIPTDETAIL].[SECTION] = [SECTIONS].[SECTION]

	LEFT JOIN [ACADEMICCALENDAR]
	ON
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM] = [ACADEMICCALENDAR].[ACADEMIC_TERM] AND
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR] = [ACADEMICCALENDAR].[ACADEMIC_YEAR] AND
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION] = [ACADEMICCALENDAR].[ACADEMIC_SESSION]

	WHERE
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION] = '01' AND
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT] = 'A' AND
	[TRANSCRIPTDETAIL].[EVENT_ID] LIKE 'LINC%' AND
	[ACADEMICCALENDAR].[TRUE_ACADEMIC_YEAR] = @EnterAcademicYear

	GROUP BY
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION]
),

/* Common Table Expression (CTE) that returns a count of online courses taken by students for each academic term. 
This will be used as a lookup table for the main query. */
CTE_ONLINE_COURSE_COUNT AS (
	SELECT
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION],
	COUNT([TRANSCRIPTDETAIL].[SECTION]) AS 'ONLINE_COURSE_COUNT'
	FROM [TRANSCRIPTDETAIL]

	WHERE
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT] = 'A' AND
	([TRANSCRIPTDETAIL].[SECTION] LIKE 'INT%' OR -- Conditons to be reviewed by OR
	[TRANSCRIPTDETAIL].[SECTION] LIKE 'IT%' OR -- Conditons to be reviewed by OR
	[TRANSCRIPTDETAIL].[SECTION] = 'HF') -- Conditons to be reviewed by OR

	GROUP BY
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION]
),

/* Common Table Expression (CTE) that returns a count of Work-integrated-learning (WIL) courses taken by students for each academic term. 
This will be used as a lookup table for the main query. */
CTE_WIL_COURSE_COUNT AS (
	SELECT
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION],
	COUNT([TRANSCRIPTDETAIL].[EVENT_SUB_TYPE]) AS 'WIL_COURSE_COUNT'
	FROM [TRANSCRIPTDETAIL]

	WHERE
	[TRANSCRIPTDETAIL].[ADD_DROP_WAIT] = 'A' AND
	[TRANSCRIPTDETAIL].[EVENT_SUB_TYPE] IN ('CLIN','LECW','PRAC') -- Conditons to be reviewed by OR

	GROUP BY
	[TRANSCRIPTDETAIL].[PEOPLE_CODE_ID],
	[TRANSCRIPTDETAIL].[ACADEMIC_TERM],
	[TRANSCRIPTDETAIL].[ACADEMIC_YEAR],
	[TRANSCRIPTDETAIL].[ACADEMIC_SESSION]
),

/* CTE for ordering all 'HOME' addresses in [ADDRESSSCHEDULE], starting from oldest ADDRESSSCHEDULE].[START_DATE]. */
CTE_ADDRESSSCHEDULE_ORDERED_HOME_ADDRESS AS (
	SELECT
	[ADDRESSSCHEDULE].[PEOPLE_ORG_CODE_ID],
	[ADDRESSSCHEDULE].[ADDRESS_TYPE],
	[ADDRESSSCHEDULE].[START_DATE],
	[ADDRESSSCHEDULE].[ZIP_CODE],
	[ADDRESSSCHEDULE].[COUNTRY],
	ROW_NUMBER() OVER(PARTITION BY [ADDRESSSCHEDULE].[PEOPLE_ORG_CODE_ID] ORDER BY [ADDRESSSCHEDULE].[START_DATE] ASC) AS [HOME_ADDRESS_START_DATE_ORDER]
	FROM [ADDRESSSCHEDULE]
	WHERE [ADDRESSSCHEDULE].[ADDRESS_TYPE] = 'HOME' AND 
	(CASE
		WHEN [ADDRESSSCHEDULE].[ZIP_CODE] IS NULL AND [ADDRESSSCHEDULE].[COUNTRY] IS NULL THEN 'ERROR_RECORD' -- Can add check on city, province, or address line if desired
		ELSE 'VALID_RECORD'
	END) = 'VALID_RECORD'
),

/* CTE that returns the oldest 'HOME' address record for each distinct [ADDRESSSCHEDULE].[PEOPLE_ORG_CODE_ID].
Some preliminary cleaning is done on the ZIP_CODE column to remove spaces and retain only the first 6 characters. */
CTE_OLDEST_HOME_ADDRESS AS (
	SELECT
	[CTE_ADDRESSSCHEDULE_ORDERED_HOME_ADDRESS].[PEOPLE_ORG_CODE_ID],
	[CTE_ADDRESSSCHEDULE_ORDERED_HOME_ADDRESS].[ZIP_CODE],
	LEFT(REPLACE([CTE_ADDRESSSCHEDULE_ORDERED_HOME_ADDRESS].[ZIP_CODE],' ',''),6) AS 'ZIP_CODE_CLEANED',
	[CTE_ADDRESSSCHEDULE_ORDERED_HOME_ADDRESS].[COUNTRY]
	FROM [CTE_ADDRESSSCHEDULE_ORDERED_HOME_ADDRESS]
	WHERE [CTE_ADDRESSSCHEDULE_ORDERED_HOME_ADDRESS].[HOME_ADDRESS_START_DATE_ORDER] = 1
),

/* CTE that returns the oldest 'HOME' address record for each distinct [ADDRESSSCHEDULE].[PEOPLE_ORG_CODE_ID], cleaned for LERS formatting.
This will be used as a lookup table for the main query. */
CTE_OLDEST_HOME_ADDRESS_CLEANED AS (
	SELECT
	[CTE_OLDEST_HOME_ADDRESS].[PEOPLE_ORG_CODE_ID],
	[CTE_OLDEST_HOME_ADDRESS].[ZIP_CODE_CLEANED],
	[CTE_OLDEST_HOME_ADDRESS].[COUNTRY],
	[CTE_CODE_COUNTRY_ACTIVE].[CODE_XVAL],
	CASE WHEN [CTE_OLDEST_HOME_ADDRESS].[COUNTRY] = 'CA' THEN 'CA' ELSE [CTE_CODE_COUNTRY_ACTIVE].[CODE_XVAL] END AS 'COUNTRY_CLEANED'
	FROM [CTE_OLDEST_HOME_ADDRESS]
	LEFT JOIN [CTE_CODE_COUNTRY_ACTIVE]
	ON
	[CTE_OLDEST_HOME_ADDRESS].[COUNTRY] = [CTE_CODE_COUNTRY_ACTIVE].[CODE_VALUE_KEY]
)

SELECT
[ACADEMICCALENDAR].[TRUE_ACADEMIC_YEAR] AS 'AcademicYear',
'KC' AS 'Provider',
[USERDEFINEDIND].[ALBERTASTUDENTID] AS 'ASN',
[ACADEMIC].[PEOPLE_ID] AS 'StudentID',
[CTE_PEOPLE].[CUSTOM_BIRTH_DATE] AS 'Birthdate',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[GENDER] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[GENDER]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[GENDER]
END AS 'Gender',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_LANGUAGE] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_LANGUAGE]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[CONVERTED_LANGUAGE]
END AS 'Language',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[CODE_XVAL] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[CODE_XVAL]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[CODE_XVAL]
END AS 'CountryOfCitizenship',
[CTE_OLDEST_HOME_ADDRESS_CLEANED].[COUNTRY_CLEANED] AS 'SourceCountry',
[CTE_OLDEST_HOME_ADDRESS_CLEANED].[ZIP_CODE_CLEANED] AS 'SourcePostalCode',
[CTE_PROGRAMLOADS].[LERSPROGRAM] AS 'ProgramID',
[CTE_PROGRAMLOADS].[LERSID] AS 'SpecializationID',
CASE
	WHEN [CTE_PROGRAMLOADS].[LERSID] = 'POW3' THEN '05'
	WHEN [CTE_PROGRAMLOADS].[LERSID] = 'POW4' THEN '05'
	WHEN [CTE_PROGRAMLOADS].[LERSID] = 'PAHET' THEN '03'
	WHEN [CTE_PROGRAMLOADS].[LERSID] = 'AHD' THEN '03'
	ELSE '02'
END AS 'ProviderLocation',
CASE
	WHEN [ACADEMIC].[ACADEMIC_TERM] = 'SUMMER' THEN '1'
	WHEN [ACADEMIC].[ACADEMIC_TERM] = 'FALL' THEN '2'
	WHEN [ACADEMIC].[ACADEMIC_TERM] = 'WINTER' THEN '3'
	WHEN [ACADEMIC].[ACADEMIC_TERM] = 'SPRING' THEN '4'
	ELSE NULL
END AS 'Session',
[ACADEMIC].[CLASS_LEVEL] AS 'YearOfStudy',
CASE
	WHEN [ACADEMIC].[FULL_PART_DISP_WITHDRAWN] = '1' THEN [FULL_PART_LOOKUP_TABLE].[CODE_XVAL]
	WHEN [ACADEMIC].[FULL_PART_DISP_WITHDRAWN] = '0' THEN [FULL_PART_NON_WITHDRAWN_LOOKUP_TABLE].[CODE_XVAL]
	ELSE NULL
END AS 'RegistrationStatus',
CASE
	WHEN [ACADEMIC].[CURRICULUM] = 'LINC13' THEN [CTE_LINC_HOURS].[LINC_HOURS]
	ELSE [ACADEMIC].[CREDITS]
END AS 'CreditsEnrolled',
CASE
	WHEN [CTE_ONLINE_COURSE_COUNT].[ONLINE_COURSE_COUNT] IS NULL THEN 'N'
	ELSE 'Y'
END AS 'OnlineDistanceDelivery',
CASE
	WHEN [CTE_WIL_COURSE_COUNT].[WIL_COURSE_COUNT] IS NULL THEN 'N'
	ELSE 'Y'
END AS 'WorkIntegratedLearning',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_VISA] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_VISA]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[CONVERTED_VISA]
END AS 'LegalStatus',
CASE
	WHEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_ETHNICITY] IS NOT NULL THEN [CTE_DEMOGRAPHICS_BY_TERM].[CONVERTED_ETHNICITY]
	ELSE [CTE_DEMOGRAPHICS_GENERAL].[CONVERTED_ETHNICITY]
END AS 'IndigenousIndicator',
CASE
	WHEN [ACADEMIC].[ENROLL_SEPARATION] = 'ENRO' THEN '0'
	WHEN [ACADEMIC].[ENROLL_SEPARATION] = 'GRAD' THEN '1'
	WHEN [ACADEMIC].[ENROLL_SEPARATION] = 'WITH' OR [ACADEMIC].[ENROLL_SEPARATION] = 'DISM' THEN '2'
	WHEN [ACADEMIC].[ENROLL_SEPARATION] = 'BRKD' THEN '5'
	ELSE [ACADEMIC].[ENROLL_SEPARATION]
END AS 'CompletionStatus'

FROM [ACADEMIC]

LEFT JOIN [ACADEMICCALENDAR]
ON
[ACADEMIC].[ACADEMIC_TERM] = [ACADEMICCALENDAR].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [ACADEMICCALENDAR].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [ACADEMICCALENDAR].[ACADEMIC_SESSION]

LEFT JOIN [CTE_PEOPLE]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_PEOPLE].[PEOPLE_CODE_ID]

LEFT JOIN [USERDEFINEDIND]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [USERDEFINEDIND].[PEOPLE_CODE_ID]

LEFT JOIN [CTE_DEMOGRAPHICS_BY_TERM]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_DEMOGRAPHICS_BY_TERM].[PEOPLE_CODE_ID] AND
[ACADEMIC].[ACADEMIC_TERM] = [CTE_DEMOGRAPHICS_BY_TERM].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [CTE_DEMOGRAPHICS_BY_TERM].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [CTE_DEMOGRAPHICS_BY_TERM].[ACADEMIC_SESSION]

LEFT JOIN [CTE_DEMOGRAPHICS_GENERAL]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_DEMOGRAPHICS_GENERAL].[PEOPLE_CODE_ID]

LEFT JOIN [CTE_PROGRAMLOADS]
ON
[ACADEMIC].[CURRICULUM] = [CTE_PROGRAMLOADS].[PROGRAMID]

LEFT JOIN [CODE_FULLPARTFLAG] AS FULL_PART_LOOKUP_TABLE
ON
[ACADEMIC].[FULL_PART] = [FULL_PART_LOOKUP_TABLE].[CODE_VALUE_KEY]

LEFT JOIN [CODE_FULLPARTFLAG] AS FULL_PART_NON_WITHDRAWN_LOOKUP_TABLE
ON
[ACADEMIC].[FULL_PART_NON_WITHDRAWN] = [FULL_PART_NON_WITHDRAWN_LOOKUP_TABLE].[CODE_VALUE_KEY]

LEFT JOIN [CODE_CURRICULUM]
ON
[ACADEMIC].[CURRICULUM] = [CODE_CURRICULUM].[CODE_VALUE_KEY]

LEFT JOIN [CTE_LINC_HOURS]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_LINC_HOURS].[PEOPLE_CODE_ID] AND
[ACADEMIC].[ACADEMIC_TERM] = [CTE_LINC_HOURS].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [CTE_LINC_HOURS].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [CTE_LINC_HOURS].[ACADEMIC_SESSION]

LEFT JOIN [CTE_ONLINE_COURSE_COUNT]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_ONLINE_COURSE_COUNT].[PEOPLE_CODE_ID] AND
[ACADEMIC].[ACADEMIC_TERM] = [CTE_ONLINE_COURSE_COUNT].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [CTE_ONLINE_COURSE_COUNT].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [CTE_ONLINE_COURSE_COUNT].[ACADEMIC_SESSION]

LEFT JOIN [CTE_WIL_COURSE_COUNT]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_WIL_COURSE_COUNT].[PEOPLE_CODE_ID] AND
[ACADEMIC].[ACADEMIC_TERM] = [CTE_WIL_COURSE_COUNT].[ACADEMIC_TERM] AND
[ACADEMIC].[ACADEMIC_YEAR] = [CTE_WIL_COURSE_COUNT].[ACADEMIC_YEAR] AND
[ACADEMIC].[ACADEMIC_SESSION] = [CTE_WIL_COURSE_COUNT].[ACADEMIC_SESSION]

LEFT JOIN [CTE_OLDEST_HOME_ADDRESS_CLEANED]
ON
[ACADEMIC].[PEOPLE_CODE_ID] = [CTE_OLDEST_HOME_ADDRESS_CLEANED].[PEOPLE_ORG_CODE_ID]

WHERE
[CODE_CURRICULUM].[LONG_DESC] NOT LIKE 'APPR%' AND
[ACADEMIC].[CURRICULUM] NOT LIKE 'DUAL%' AND
([ACADEMIC].[ACADEMIC_SESSION] = '01' OR
[ACADEMIC].[PROGRAM] = 'CREDIT' OR
[ACADEMIC].[DEGREE] <> 'CONED') AND
[ACADEMIC].[ACADEMIC_SESSION] <> '' AND
[ACADEMIC].[STATUS] <> 'N' AND
[ACADEMIC].[ACADEMIC_FLAG] = 'Y' AND
[ACADEMIC].[ENROLL_SEPARATION] IN ('APPR','BRKD','DISM','ENRO','GRAD','WITH') AND
(CASE
	WHEN [ACADEMIC].[FULL_PART_DISP_WITHDRAWN] = '1' THEN [FULL_PART_LOOKUP_TABLE].[CODE_XVAL]
	WHEN [ACADEMIC].[FULL_PART_DISP_WITHDRAWN] = '0' THEN [FULL_PART_NON_WITHDRAWN_LOOKUP_TABLE].[CODE_XVAL]
	ELSE NULL
END) IN ('F','L','N','P') AND
[ACADEMICCALENDAR].[TRUE_ACADEMIC_YEAR] = @EnterAcademicYear

ORDER BY [ACADEMIC].[PEOPLE_ID] ASC
